---
- include: "{{item}}"
  with_first_found:
    - files:
        - "{{ansible_distribution}}_packages.yml"
        - "{{ansible_os_family}}_packages.yml"

- include: answers.yml
#- include: installer.yml
